// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {xk} from '../models';
import {fdu} from '../models';

export function ClassSchedule(arg1:Array<xk.Course>):Promise<Array<any>>;

export function GetGrades():Promise<fdu.Grades>;

export function GetRank():Promise<fdu.Rank>;

export function Login():Promise<void>;

export function Logout():Promise<void>;

export function OperateCourse(arg1:number,arg2:boolean):Promise<void>;

export function QueryCourses(arg1:xk.Query):Promise<Array<xk.Course>>;

export function Select(arg1:xk.Query):Promise<void>;
