// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClassSchedule(arg1) {
  return window['go']['xk']['XK']['ClassSchedule'](arg1);
}

export function GetGrades() {
  return window['go']['xk']['XK']['GetGrades']();
}

export function GetRank() {
  return window['go']['xk']['XK']['GetRank']();
}

export function Login() {
  return window['go']['xk']['XK']['Login']();
}

export function Logout() {
  return window['go']['xk']['XK']['Logout']();
}

export function OperateCourse(arg1, arg2) {
  return window['go']['xk']['XK']['OperateCourse'](arg1, arg2);
}

export function QueryCourses(arg1) {
  return window['go']['xk']['XK']['QueryCourses'](arg1);
}

export function Select(arg1) {
  return window['go']['xk']['XK']['Select'](arg1);
}
