// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utils} from '../models';

export function Login(arg1:Array<string>):Promise<utils.User>;

export function Logout():Promise<void>;
