// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGrades() {
  return window['go']['fdu']['Fdu']['GetGrades']();
}

export function GetRank() {
  return window['go']['fdu']['Fdu']['GetRank']();
}

export function Login(arg1) {
  return window['go']['fdu']['Fdu']['Login'](arg1);
}

export function Logout() {
  return window['go']['fdu']['Fdu']['Logout']();
}
